[build-system]
requires = ["flit_core >=3.2,<4", "serial", "smbus", "datetime", "bme280"]
build-backend = "flit_core.buildapi"

[project]
name = "tinyweb"
authors = [{name = "Elyas Bianchi", email = "elyasb99@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

